
[[conventions]]
== Terms and definitions

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*",
"*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*NOT RECOMMENDED*", "*MAY*",
and "*OPTIONAL*" in this document are to be interpreted as
described in BCP 14 <<RFC2119>> <<RFC8174>> when, and only when, they
appear in all capitals, as shown here.

The key words "*Private Use*", "*Experimental Use*",
"*Hierarchical Allocation*", "*First Come First Served*",
"*Expert Review*", "*Specification Required*", "*RFC Required*",
"*IETF Review*", "*Standards Action*" and "*IESG Approval*" in
this document are to be interpreted as described in <<RFC8126,4>>.

Notation in this document is described in ABNF <<RFC5234>> as used by
<<RFC6350>>.

Definitions from <<RFC6350>> apply to this specification except when
explicitly overridden.

All names of properties, property parameters, enumerated property
values, and property parameter values are case-insensitive. However,
all property values are case-sensitive, unless otherwise stated.


=== Definitions

vObject::
  information modelling language developed by CalConnect

vFormat::
  serialization format used for vObject

inner component, sub-component::
  a vObject located within a vObject

outer component, super-component::
  a vObject that this vObject is located within

client user application (CUA)::
  the vObject client implementation that interfaces with the user
